name: Explore Repository 
on: 
  push:

jobs: 
  explore: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Show current directory
        run: pwd 
      - name: List repository
        run: la -la
      - name: Show message
        run: exho "Repository files are available!" 
